name = "site-diagnostics"
main = "api/main.workers.ts"
compatibility_date = "2025-04-01"
compatibility_flags = ["nodejs_compat"]

[build]
command = "bun scripts/build-workers.ts"

[[rules]]
type = "Text"
globs = ["**/*.html"]
fallthrough = true

[[rules]]
type = "Data"
globs = ["**/*.ttf"]
fallthrough = true

[[rules]]
type = "Data"
globs = ["**/*.png"]
fallthrough = true

[[rules]]
type = "CompiledWasm"
globs = ["**/*.wasm"]
fallthrough = true

[observability]
enabled = true

[[routes]]
pattern = "site-diagnostics.decocms.com"
custom_domain = true

[[d1_databases]]
binding = "D1"
database_name = "site-diagnostics"
database_id = "b703371e-0bbe-4eab-9a4b-8aee9643cb22"
migrations_dir = "migrations/d1"

[[kv_namespaces]]
binding = "CACHE"
id = "75797ec99ceb414bb23d40744f9d369f"
